; PlatformIO Project Configuration File
; Smart Speaker — ESP32 Arduino

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -I src
    -I include
    -std=c++17
